### ISSUE TITLE
Bring my articles from Medium

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/medium-blog#43]
## TODOS
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 1 — Prólogo](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-parte-1-c40837ac1a92)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 2 — Matrix Origins: Onde tudo começou](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-2-f727cf9e36cf)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 3 (1/2) — O que você quer ser quando crescer? Colegial](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-parte-3-1-623d467ba5d6)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 3 (2/2) — O que você quer ser quando crescer? Pós Ensino Médio](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-parte-3-2-7c1510c2799d)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 4 — Vida universitária e Sistemas de informação](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-4-d20932bfdd41)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 5— Entrando na área de TI: Parte 1 — Networking e Entrevista](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-5-p1-35b0c858e1fc)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa Ato 5 — Entrando na área de TI: Parte 2 — O trabalho](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-5-p2-e394647e7c1a)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 6: Estudos específicos, como eu fiz, faço e dicas](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-6-9b49e7dd42a8)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 7 — A Jornada do Inglês: Parte 2: Estudando inglês na Irlanda e reflexões](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-7-parte-2-13baa58d9e9c)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 7 — A Jornada do Inglês: Parte 1: Aprendendo inglês no Brasil](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-7-parte-1-2933f155e466)
- [x] [Desenvolvedor JavaScript — do Brasil à Europa - Ato 8 — Bye bye Brasil: Planejando o intercâmbio e dicas](https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-8-4b830c2ad62f)
- [x] [CSS Basics: Position Absolute e Relative](https://medium.com/trainingcenter/css-basics-position-absolute-e-relative-d725a2fcc8e)
- [x] [Entendendo de uma vez por todas Expressões Regulares: Parte 1 — Introdução](https://medium.com/trainingcenter/entendendo-de-uma-vez-por-todas-express%C3%B5es-regulares-parte-1-introdu%C3%A7%C3%A3o-dfe63e289dc3)
- [x] [Entendendo de uma vez por todas Expressões Regulares: Parte 2 — Metacharacters](https://medium.com/trainingcenter/entendendo-de-uma-vez-por-todas-express%C3%B5es-regulares-3538d42870f3  )
- [x] [Entendendo de uma vez por todas Expressões Regulares: Parte 3 — Classes de Caractere](https://medium.com/trainingcenter/expressoes-regulares-parte-3-8fbd6b20a5f6)
- [x] [Entendendo de uma vez por todas Expressões Regulares: Parte 4— Quantifiers](https://medium.com/trainingcenter/expressoes-regulares-parte-4-92c41516e80c)
- [x] [Entendendo de uma vez por todas Expressões Regulares: Parte 5— Capturando Grupos](https://medium.com/trainingcenter/entendendo-de-uma-vez-por-todas-express%C3%B5es-regulares-parte-5-5ffd39138f2)
- [x] [Entendendo de uma vez por todas Expressões Regulares: Parte 6— Âncoras](https://medium.com/trainingcenter/expressoes-regulares-parte-6-85804a357767)
- [x] [Entendendo de uma vez por todas Expressões Regulares: Parte 7— Regex no mundo JavaScript](https://medium.com/trainingcenter/entendendo-de-uma-vez-por-todas-express%C3%B5es-regulares-parte-7-66be1ac1f72d)
- [x] [Você precisa conhecer o Franz!](https://medium.com/trainingcenter/conheca-o-franz-f5fcf7cb512b)
- [x] [Subindo seu projeto Front-end gratuitamente com Github Pages](https://medium.com/trainingcenter/subindo-seu-projeto-front-github-pages-1b61e2e1c447)
- [x] [Subindo seu projeto Front-end gratuitamente com Surge.sh](https://medium.com/trainingcenter/subindo-seu-projeto-front-surge-52d47cf31e0b)
- [x] [Coisas que eu não que eu não sei em TI e no geral (2018)](https://medium.com/@raul_fdm/coisas-que-eu-n%C3%A3o-que-eu-n%C3%A3o-sei-em-ti-e-no-geral-66a068cb3068)

**Comment by raulfdm** [comment]
https://medium.com/trainingcenter/dev-js-do-brasil-a-europa-ato-7-parte-3-6d61d3f0f706 must be moved out of the series.

Isn't 100% related with the exchange.
